// <auto-generated />
using Assignment2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Project_6_1_FAQ.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20251008013255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment2.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Assignment2.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FAQId = 1,
                            Answer = "Bootstrap is a free, open-source front-end framework for developing websites and web applications.",
                            CategoryId = "gen",
                            Question = "What is Bootstrap?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FAQId = 2,
                            Answer = "Bootstrap was originally released in August 2011.",
                            CategoryId = "hist",
                            Question = "When was Bootstrap released?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FAQId = 3,
                            Answer = "Bootstrap was created by Mark Otto and Jacob Thornton at Twitter.",
                            CategoryId = "hist",
                            Question = "Who created Bootstrap?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FAQId = 4,
                            Answer = "JavaScript is a high-level, interpreted programming language used to make web pages interactive.",
                            CategoryId = "gen",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            FAQId = 5,
                            Answer = "JavaScript was created in 1995 by Brendan Eich while he was working at Netscape.",
                            CategoryId = "hist",
                            Question = "When was JavaScript created?",
                            TopicId = "js"
                        },
                        new
                        {
                            FAQId = 6,
                            Answer = "No, JavaScript and Java are completely different programming languages with different purposes and syntax.",
                            CategoryId = "gen",
                            Question = "Is JavaScript the same as Java?",
                            TopicId = "js"
                        },
                        new
                        {
                            FAQId = 7,
                            Answer = "jQuery is a fast, small, and feature-rich JavaScript library that simplifies HTML document manipulation and event handling.",
                            CategoryId = "gen",
                            Question = "What is jQuery?",
                            TopicId = "jquery"
                        },
                        new
                        {
                            FAQId = 8,
                            Answer = "jQuery was created by John Resig and released in 2006.",
                            CategoryId = "hist",
                            Question = "Who developed jQuery?",
                            TopicId = "jquery"
                        });
                });

            modelBuilder.Entity("Assignment2.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "bootstrap",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "js",
                            Name = "JavaScript"
                        },
                        new
                        {
                            TopicId = "jquery",
                            Name = "jQuery"
                        });
                });

            modelBuilder.Entity("Assignment2.Models.FAQ", b =>
                {
                    b.HasOne("Assignment2.Models.Category", "Category")
                        .WithMany("FAQs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.Models.Topic", "Topic")
                        .WithMany("FAQs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Assignment2.Models.Category", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("Assignment2.Models.Topic", b =>
                {
                    b.Navigation("FAQs");
                });
#pragma warning restore 612, 618
        }
    }
}
